### PR TITLE
Disable CONFIG_FPE_NWFPE for ARCH=arm all{mod,yes}config for now

### PR DESCRIPTION
**Pull request by nathanchance**
There is a compiler inserted call to `__aeabi_uldivmod`, which causes an
error at link time because the kernel does not link against compiler-rt.

Disable this configuration until it can be dealt with.

Link: https://github.com/ClangBuiltLinux/linux/issues/1666

### CODE REVIEW

**Review by nickdesaulniers — APPROVED** [review]
thanks for the patch!

**Comment by nickdesaulniers** [comment]
any idea about the presubmit failure?

**Comment by nathanchance** [comment]
> any idea about the presubmit failure?

`scripts/generate.sh` is updating `LLVM_TOT_VERSION` to `16` then updating all of the `clang-nightly` references to `clang-15`. I'll fix it in a separate pull request.

Thanks for the review!

**Comment by nathanchance** [comment]
#389, I'll rebase this pull request on that one just to make sure everything works properly.

**Comment by nathanchance** [comment]
Actually, I'll rebase that pull request on this one.

**Pull request merged**
