### PR TITLE
Work around tuxbuild bug with "LLVM: 1", by ensuring 1 is a string.

### PR DESCRIPTION
**Pull request by danrue**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
if you modify https://github.com/ClangBuiltLinux/continuous-integration2/blob/main/generate_tuxbuild.py#L47

```diff
-                     arch, toolchain, kconfig, int(build["llvm"])))
+                     arch, toolchain, kconfig, str(int(build["llvm"]))))
```
You can then autogenerate these configs via: `$ ./generate_tuxbuild.py next < generator.yml > next.tux.yml` and `./generate_tuxbuild.py mainline < generator.yml > mainline.tux.yml`.

**Comment by danrue** [comment]
> if you modify https://github.com/ClangBuiltLinux/continuous-integration2/blob/main/generate_tuxbuild.py#L47
> 
> ```diff
> -                     arch, toolchain, kconfig, int(build["llvm"])))
> +                     arch, toolchain, kconfig, str(int(build["llvm"]))))
> ```
> 
> You can then autogenerate these configs via: `$ ./generate_tuxbuild.py next < generator.yml > next.tux.yml` and `./generate_tuxbuild.py mainline < generator.yml > mainline.tux.yml`.

Oh please go ahead, I'm signing off for the weekend. Sorry for the bug in any case, it should have worked either way.

**Comment by nathanchance** [comment]
That does not appear to work. I have to explicitly escape it.

```diff
diff --git a/generate_tuxbuild.py b/generate_tuxbuild.py
index 7ce7630..a4d67d1 100755
--- a/generate_tuxbuild.py
+++ b/generate_tuxbuild.py
@@ -43,7 +43,7 @@ sets:
             toolchain = "clang-"
             toolchain += "nightly" if build["llvm_version"] == max_version else str(build["llvm_version"])
             kconfig = build["config"]
-            print("      - {{target_arch: {0}, toolchain: {1}, kconfig: {2}, make_variables: {{LLVM: {3}}}}}".format(\
+            print("      - {{target_arch: {0}, toolchain: {1}, kconfig: {2}, make_variables: {{LLVM: \"{3}\"}}}}".format(\
                     arch, toolchain, kconfig, int(build["llvm"])))

 if __name__ == "__main__":
```

Pushing now.

**Review by nickdesaulniers — APPROVED** [review]
thanks!

**Pull request merged**
