### PR TITLE
[v2] Build most powerpc64le configs with LLVM=1 LLVM_IAS=1

### PR DESCRIPTION
**Pull request by nathanchance**
On mainline, SUSE's configuration needs to build with LLVM_IAS=0 because
of https://github.com/ClangBuiltLinux/linux/issues/1418.

Closes: https://github.com/ClangBuiltLinux/continuous-integration2/issues/265

### CODE REVIEW

**Comment by nathanchance** [comment]
Now that we have a solution to https://github.com/ClangBuiltLinux/linux/issues/1581, I have applied it so that we can use the first version of the pull, which won't have the boot failures.

**Comment by nathanchance** [comment]
Alright, `next-20220310` boots without any patches so I have applied Alexey's patch to mainline. We can drop it once it is merged.

**Comment by nathanchance** [comment]
I added the patch that drops the `stabs` annotations so that all of these configurations can be built with `LLVM=1 LLVM_IAS=1`. We should only have to carry that patch for a couple of weeks. This should be ready to go in.

**Review by nickdesaulniers — APPROVED** [review]
LGTM; thanks! :palm_tree: :cook_islands:

**Pull request merged**
