### PR TITLE
Add x86 vDSO patch for tip of tree ld.lld default change

### PR DESCRIPTION
**Pull request by nathanchance**
mainline and -next also need this technically but the patch is in the x86/urgent branch so it should make 6.1, which is on Sunday so I do not see a point in adding it; the builds can just fail until then. -next is not getting updated again until Tuesday so similar situation as mainline.

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Will a patch in patches/stable conflict with a patch in patches/5.15?

**Comment by nickdesaulniers** [comment]
> Will a patch in patches/stable conflict with a patch in patches/5.15?

I assume no, but I forget how the patch application works.

**Review by nickdesaulniers — APPROVED** [review]
LGTM; thanks :wolf: :lobster:

**Comment by nathanchance** [comment]
> Will a patch in patches/stable conflict with a patch in patches/5.15?

Nope, separate trees. stable is the latest stable release, not latest LTS release, which is still currently 5.15.

**Comment by nickdesaulniers** [comment]
> > Will a patch in patches/stable conflict with a patch in patches/5.15?
> 
> Nope, separate trees. stable is the latest stable release, not latest LTS release, which is still currently 5.15.

ah, right, stable is a floating version.

**Pull request merged**
