### PR TITLE
Update stable to 6.7 and add separate 6.6 builds

### PR DESCRIPTION
**Pull request by nathanchance**
6.7 is the latest stable release.

Commits

  14a6d70 ("Add arm64 virtconfig")
  19cc1de ("Add arm64_hardening mainline and next branch")
  0b963aa ("Add x86_64_hardening mainline and next branch")

are applied because these configurations are all available in 6.7.

6.6 is the latest LTS release. All builds have been copied from stable to ensure no coverage is lost.

The diff of `estimate-builds.py` from this pull request:

```
diff --git a/tmp/estimate-builds.txt b/tmp/.psub.RdOBXOBZTQ
index e7a1f51..5f11a73 100644
--- a/tmp/estimate-builds.txt
+++ b/tmp/.psub.RdOBXOBZTQ
@@ -1,4 +1,4 @@
-Total builds per week: 9455
+Total builds per week: 10081

   - tree: mainline
     total: 3360
@@ -26,11 +26,23 @@ Total builds per week: 9455
     - clang-android: 115

   - tree: stable
-    total: 612
+    total: 621
     breakdown:
-    - clang-18: 138
-    - clang-17: 138
-    - clang-16: 65
+    - clang-18: 144
+    - clang-17: 140
+    - clang-16: 66
+    - clang-15: 60
+    - clang-14: 54
+    - clang-13: 54
+    - clang-12: 52
+    - clang-11: 51
+
+  - tree: 6.6
+    total: 617
+    breakdown:
+    - clang-18: 140
+    - clang-17: 140
+    - clang-16: 66
     - clang-15: 60
     - clang-14: 54
     - clang-13: 54
```

### CODE REVIEW

**Comment by JustinStitt** [comment]
I'm confused:
> [14a6d70](https://github.com/ClangBuiltLinux/continuous-integration2/commit/14a6d700ca303a6d86058a0c5008a89f5a356a22) ("Add arm64 virtconfig") [19cc1de](https://github.com/ClangBuiltLinux/continuous-integration2/commit/19cc1dec2e057741a3cdba12fd89c4c79f20cf52) ("Add arm64_hardening mainline and next branch") [0b963aa](https://github.com/ClangBuiltLinux/continuous-integration2/commit/0b963aa4cee46cd301069a7e64e5edf36d503e72) ("Add x86_64_hardening mainline and next branch")
> 

were these commits not applied in #613 and #657?

I see them in main: https://github.com/ClangBuiltLinux/continuous-integration2/blob/main/generator.yml

**Comment by nathanchance** [comment]
Sorry, perhaps that could be clarified by adding "to the `stable` builds", as those commits only applied the changes to `next` and `mainline`.

**Review by JustinStitt — APPROVED** [review]
LGTM!

This will add a few more builds but our new caching efforts (which are especially effective on `stable` builds) should mean we aren't risking blowing budget.

**Comment by JustinStitt** [comment]
> Commits
> 
> [14a6d70](https://github.com/ClangBuiltLinux/continuous-integration2/commit/14a6d700ca303a6d86058a0c5008a89f5a356a22) ("Add arm64 virtconfig") [19cc1de](https://github.com/ClangBuiltLinux/continuous-integration2/commit/19cc1dec2e057741a3cdba12fd89c4c79f20cf52) ("Add arm64_hardening mainline and next branch") [0b963aa](https://github.com/ClangBuiltLinux/continuous-integration2/commit/0b963aa4cee46cd301069a7e64e5edf36d503e72) ("Add x86_64_hardening mainline and next branch")
> 
> are applied because these configurations are all available in 6.7.

Gotcha, does the following re-wording illustrate the changes effectively? @nathanchance 

```
Following the spirit of commits:

https://github.com/ClangBuiltLinux/continuous-integration2/commit/14a6d700ca303a6d86058a0c5008a89f5a356a22 ("Add arm64 virtconfig")
https://github.com/ClangBuiltLinux/continuous-integration2/commit/19cc1dec2e057741a3cdba12fd89c4c79f20cf52 ("Add arm64_hardening mainline and next branch")
https://github.com/ClangBuiltLinux/continuous-integration2/commit/0b963aa4cee46cd301069a7e64e5edf36d503e72 ("Add x86_64_hardening mainline and next branch")

... also do the same for stable builds.
```

**Comment by nathanchance** [comment]
Yup, that seems reasonable!

**Comment by nathanchance** [comment]
I updated the commit message of 80370acea56aef710027ad70ad7b4d637e0ce75b to be a little clearer (I did not use the exact suggested wording but I hope it is still okay) and I updated the badges for the README since I forgot to do that in the initial pull.

**Pull request merged**
