### PR TITLE
Apply virtconfig to defconfig arm64

### PR DESCRIPTION
**Pull request by phongt**
Apply for #524 

Change generator.yml  and for mainline branch only because virtconfig is available in v6.3-rc1

### CODE REVIEW

**Review by nathanchance — CHANGES_REQUESTED** [review]
Thanks for the patch!

However, I don't think this change is quite right. I think `virtconfig` should be its own build target, otherwise we are losing build coverage, as [`virt.config` turns off a bunch of configurations](https://elixir.bootlin.com/linux/v6.5-rc5/source/arch/arm64/configs/virt.config) that are not necessary for running in a virtual machine. Truthfully, given that `virtconfig` is [by definition a subset of `defconfig`](https://elixir.bootlin.com/linux/v6.5-rc5/source/arch/arm64/Makefile#L210), I am not really sure there is much value in testing both.

If we do want to test both, I think we should just copy the `arm64` anchor, name it `arm64_virt`, change the target to `virtconfig`, and add it to all trees that support it. The automation notes that this change as it stands applies to all uses of `arm64`, which is not correct for older trees.

**Comment by phongt** [comment]
just change again with new `arm64_virt` and apply for mainline/next with llvm tot/llvm-latest/llvm-16

**Review by nathanchance — APPROVED** [review]
The comment about what this actual gains us remains but otherwise, seems good to me! Thanks!

**Comment by nickdesaulniers** [comment]
sorry for not merging this sooner! I had forgotten about it!

**Pull request merged**
