### PR TITLE
Install requirements.txt for check cache stage

### PR DESCRIPTION
**Pull request by nathanchance**
`requests` is not the only module that is needed:

```
  Traceback (most recent call last):
    File "/__w/continuous-integration2/continuous-integration2/check_cache.py", line 41, in <module>
      from utils import get_workflow_name_to_var_name, update_repository_variable
    File "/__w/continuous-integration2/continuous-integration2/utils.py", line 8, in <module>
      import yaml
  ModuleNotFoundError: No module named 'yaml'
```

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/7271701478

If the variable is not created during the cache setup stage, the update cache stage will fail with a 404 error:

```
  Trying to update cache with status: pass
  Traceback (most recent call last):
    File "update_cache.py", line 88, in <module>
      main()
    File "update_cache.py", line 83, in main
      update_cache("pass", git_sha, clang_version)
    File "update_cache.py", line 44, in update_cache
      update_repository_variable(
    File "/__w/continuous-integration2/continuous-integration2/utils.py", line 218, in update_repository_variable
      with urllib.request.urlopen(request) as response:
    File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/local/lib/python3.8/urllib/request.py", line 531, in open
      response = meth(req, response)
    File "/usr/local/lib/python3.8/urllib/request.py", line 640, in http_response
      response = self.parent.error(
    File "/usr/local/lib/python3.8/urllib/request.py", line 569, in error
      return self._call_chain(*args)
    File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
      result = func(*args)
    File "/usr/local/lib/python3.8/urllib/request.py", line 649, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 404: Not Found
```

I am not sure if we want to harden `update_cache.py` a little bit more against this scenario by creating the variable if it does not already exist?

### CODE REVIEW

**Comment by nathanchance** [comment]
I also added a couple of stylistic changes to this PR while I was in the area. I could have done it as a separate pull but I figured I would regenerate the workflow files just once.

**Comment by JustinStitt** [comment]
Ok, with the yaml module update_cache should now always have a cache entry to reference because check_cache always creates one.

LGTM

**Comment by JustinStitt** [comment]
I'll look for opportunities to harden update_cache a bit too. It's failures shouldn't be killing our workflows

**Comment by JustinStitt** [comment]
@nathanchance Any idea why only this workflow failed with no yaml package? Shouldn't they all be failing? Maybe the tuxsuite box for android doesn't have yaml pre-installed?

**Review by JustinStitt — APPROVED** [review]

**Comment by nathanchance** [comment]
> @nathanchance Any idea why only this workflow failed with no yaml package? Shouldn't they all be failing? Maybe the tuxsuite box for android doesn't have yaml pre-installed?

I did not look into it too much but I thought the same thing...

**Pull request merged**
