### PR TITLE
Combine certain YAML files further

### PR DESCRIPTION
**Pull request by nathanchance**
I think `tree_schedules` should be a part of `trees` and the `chromeos_configs` and `kasan_configs` should be a part of `configs`. This slims up the number of overall files and puts things that should be updated together in the same file.

### CODE REVIEW

**Comment by JustinStitt** [comment]
Taking a look at the repo as a whole, maybe these `000\d.*.yml`'s shouldn't be in the top-level directory. I need about an extra half rotation of my scroll wheel to get to the CI matrix 😅.

I think it may _also_ be worth combining all the `0009-llvm-\d\d.yml`'s into a single one. Yeah, it'll be large but I feel like it'd be cleaner. Open to feedback to my feedback, of course.

**Comment by nathanchance** [comment]
> Taking a look at the repo as a whole, maybe these `000\d.*.yml`'s shouldn't be in the top-level directory. I need about an extra half rotation of my scroll wheel to get to the CI matrix 😅.

Yeah I was just think that as I am writing out documentation. I think I will push a restructuring as part of that pull request.

> I think it may _also_ be worth combining all the `0009-llvm-\d\d.yml`'s into a single one. Yeah, it'll be large but I feel like it'd be cleaner. Open to feedback to my feedback, of course.

Having separate files for each LLVM version in the matrix was the main desire from breaking apart `generator.yml`. The current scheme will make adding new LLVM versions like for #686 a lot easier.

**Comment by JustinStitt** [comment]
I'm now thinking of some new system where we don't have to specify every single build for each llvm version.

Maybe some syntax like:

```yml
{<< : *arm32_v5,          << : *mainline,         << : *llvm,            boot: true,  << : *llvm_all} # specifies all supported llvm versions

{<< : *arm32_v7,          << : *mainline,         << : *llvm_full,       boot: true,  << : *llvm_13, *llvm_14, *llvm_15} # only do builds for 13, 14, 15
```

I have NO idea if yml supports this type of thing or if we would need to invent another system.

Thoughts?

**Comment by nathanchance** [comment]
This is tentatively what I have as the structure I am writing documentation around now:

```
./
├── caching/
│   ├── check.py
│   ├── update.py
│   └── utils.py -> ../utils.py
├── generator/
│   ├── generate.py*
│   ├── generate_tuxsuite.py*
│   ├── generate_workflow.py*
│   ├── LLVM_TOT_VERSION
│   ├── utils.py -> ../utils.py
│   └── yml/
├── LICENSE.txt
├── mock.builds.json
├── patches/
│   ├── 5.4/
│   │   ├── 20240126_nathan_powerpc_use_always_instead_of_always_y_in_for_crtsavres_o.patch
│   │   └── series
│   ├── 6.1/
│   │   ├── series
│   │   └── um-clang-18.patch
│   ├── 6.6/
│   │   ├── 20240111_nathan_media_mxl5xx_move_xpt_structures_off_stack.patch
│   │   ├── 20240123_keescook_smb_work_around_clang___bdos_type_confusion.patch
│   │   ├── 20240123_nathan_modpost_add_ltext_and_ltext_to_text_sections.patch
│   │   ├── 20240123_nathan_um_fix_adding_no_pie_for_clang.patch
│   │   ├── 6a4e59eeedc3018cb57722eecfcbb49431aeb05f.patch
│   │   └── series
│   ├── android12-5.10/
│   │   ├── 0001-x86-mm-Simplify-RESERVE_BRK.patch
│   │   ├── 0002-x86-mm-Fix-RESERVE_BRK-for-older-binutils.patch
│   │   └── series
│   ├── android13-5.10/
│   │   ├── 0001-x86-mm-Simplify-RESERVE_BRK.patch
│   │   ├── 0002-x86-mm-Fix-RESERVE_BRK-for-older-binutils.patch
│   │   └── series
│   ├── arm64/
│   │   ├── 20240123_keescook_smb_work_around_clang___bdos_type_confusion.patch
│   │   └── series
│   ├── arm64-fixes/
│   │   ├── 20240123_keescook_smb_work_around_clang___bdos_type_confusion.patch
│   │   └── series
│   ├── mainline/
│   │   ├── 20231115_chenhuacai_loongarch_kvm_fix_build_due_to_api_changes.patch
│   │   ├── 20240111_nathan_media_mxl5xx_move_xpt_structures_off_stack.patch
│   │   ├── 20240123_keescook_smb_work_around_clang___bdos_type_confusion.patch
│   │   ├── 20240123_nathan_modpost_add_ltext_and_ltext_to_text_sections.patch
│   │   ├── 20240123_nathan_um_fix_adding_no_pie_for_clang.patch
│   │   └── series
│   ├── next/
│   │   ├── 20240111_nathan_media_mxl5xx_move_xpt_structures_off_stack.patch
│   │   ├── 20240123_nathan_modpost_add_ltext_and_ltext_to_text_sections.patch
│   │   ├── 20240123_nathan_um_fix_adding_no_pie_for_clang.patch
│   │   └── series
│   ├── stable/
│   │   ├── 20240111_nathan_media_mxl5xx_move_xpt_structures_off_stack.patch
│   │   ├── 20240123_keescook_smb_work_around_clang___bdos_type_confusion.patch
│   │   ├── 20240123_nathan_modpost_add_ltext_and_ltext_to_text_sections.patch
│   │   ├── 20240123_nathan_um_fix_adding_no_pie_for_clang.patch
│   │   └── series
│   └── tip/
│       ├── 20240123_keescook_smb_work_around_clang___bdos_type_confusion.patch
│       └── series
├── README.md
├── requirements.txt
├── ruff.toml
├── scripts/
│   ├── badge-caching/
│   │   ├── failing.svg
│   │   ├── passing.svg
│   │   └── refresh.sh
│   ├── build-local.py*
│   ├── check-logs.py*
│   ├── check-matrix.py*
│   ├── check-patches.py*
│   ├── estimate-builds.py*
│   ├── generate-boot-utils-json.py*
│   ├── markdown-badges.py*
│   ├── parse-debian-clang.py*
│   └── utils.py -> ../utils.py
├── tuxsuite/
└── utils.py

19 directories, 63 files
```

**Pull request merged**
