### PR TITLE
Add support for `ARCH=um`

### PR DESCRIPTION
**Pull request by nathanchance**
Now that `ARCH=um` builds with clang, let's make sure it stays working!

NOTE: This PR depends on [this PR](https://lore.kernel.org/r/202203210821.9E5FDCA863@keescook/) for mainline; once it is merged, this one can be too.

### CODE REVIEW

**Review by nickdesaulniers — APPROVED** [review]
if you remove the closes tag, then in a follow up, we can work on boot testing this?

**Comment by nickdesaulniers** [comment]
Probably want to update some docs. Homepage and kernel docs?

**Comment by nathanchance** [comment]
> if you remove the closes tag, then in a follow up, we can work on boot testing this?

Sure, I can remove the closes tag. I don't think that we can boot test this with our current flow, as UML is a virtual machine within itself, so we would not use QEMU for testing. I'll look into that tomorrow.

**Comment by nathanchance** [comment]
Yup, I have this working locally:

```
$ tuxmake -a um -C $CBL_SRC/linux-next -k defconfig -r podman -t clang-nightly LLVM=1 kernel
...


# sudo is critical here, the root_fs needs to be owned by root to work properly
$ sudo sh -c "mkdir root_fs && zstd -c -d $CBL_GIT/boot-utils/images/x86_64/rootfs.cpio.zst | cpio -D root_fs -di"
...
I: config: PASS in 0:00:02.285515
I: default: PASS in 0:00:15.879420
I: kernel: PASS in 0:00:04.387773
I: build output in /home/nathan/.cache/tuxmake/builds/56

$ $HOME/.cache/tuxmake/builds/56/linux rootfstype=hostfs rootflags=$PWD/root_fs
Core dump limits :
        soft - NONE
        hard - NONE
Checking that ptrace can change system call numbers...OK
Checking syscall emulation patch for ptrace...OK
Checking advanced syscall emulation patch for ptrace...OK
Checking environment variables for a tempdir...none found
Checking if /dev/shm is on tmpfs...OK
Checking PROT_EXEC mmap in /dev/shm...OK
Adding 25071616 bytes to physical memory to account for exec-shield gap
Linux version 5.17.0-rc6-00019-g7c23c8af7393-dirty (tuxmake@tuxmake) (Debian clang version 15.0.0-++20220321071824+df4814d45d6b-1~exp1~20220321071914.194, Debian LLD 15.0.0) #1 @1647970143
Zone ranges:
  Normal   [mem 0x0000000000000000-0x00000000637e8fff]
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x0000000000000000-0x00000000037e8fff]
Initmem setup node 0 [mem 0x0000000000000000-0x00000000037e8fff]
Built 1 zonelists, mobility grouping on.  Total pages: 14117
Kernel command line: rootfstype=hostfs rootflags=/home/nathan/tmp/root_fs root=98:0 console=tty
...
Run /sbin/init as init process
Starting syslogd: OK
Starting klogd: OK
Running sysctl: OK
Saving random seed: SKIP (read-only file system detected)
Starting network: OK
Linux version 5.17.0-rc6-00019-g7c23c8af7393-dirty (tuxmake@tuxmake) (Debian clang version 15.0.0-++20220321071824+df4814d45d6b-1~exp1~20220321071914.194, Debian LLD 15.0.0) #1 @1647970143
Linux version 5.17.0-rc6-00019-g7c23c8af7393-dirty (tuxmake@tuxmake) (Debian clang version 15.0.0-++20220321071824+df4814d45d6b-1~exp1~20220321071914.194, Debian LLD 15.0.0) #1 @1647970143
Stopping network: OK
Saving random seed: SKIP (read-only file system detected)
Stopping klogd: OK
Stopping syslogd: OK
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system poweroff
reboot: System halted
```

I will wire this up into boot-utils shortly as `boot-uml.sh`, then I will update this PR.

**Comment by nathanchance** [comment]
Alright, this now depends on https://github.com/ClangBuiltLinux/boot-utils/pull/59. Once that is good to go, I'll bump `boot-utils` here, then this pull request should be mergeable!

**Comment by nathanchance** [comment]
Alright, `boot-utils` has been updated and I have added a patch for a next regression. This should be mergeable, please let me know what you think.

**Review by nickdesaulniers — APPROVED** [review]
nice work! consider dropping all the intermediary regen patches that just churn the dotfiles. 🛡️ 🚢

**Comment by nathanchance** [comment]
Thanks for the review as always!

**Pull request merged**
