### PR TITLE
Add hardening.config

### PR DESCRIPTION
**Pull request by phongt**
Apply for branch: kernel mainline and next
config: [arm64 hardening.config](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm64/configs/hardening.config), [x86_64 hardening.config](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/configs/hardening.config)

### CODE REVIEW

**Comment by kees** [comment]
Hm, I think allmodconfig is a superset of the hardening.config configs -- is there a useful difference here where we gain meaningful build coverage?

**Comment by nathanchance** [comment]
I suppose boot testing would be the major gain because we don't boot test allmodconfig. However, it'd be interesting to see the difference of what actually gets enabled in defconfig and see if those configs are really worth testing in our simple VMs.

**Comment by kees** [comment]
Yeah, boot testing does make sense here. I hadn't considered that. Yeah, let's do it! :)

**Review by nathanchance — APPROVED** [review]
LGTM, thanks! If this works out for LLVM ToT, I think we should turn this on for stable LLVM as well.

**Pull request merged**
