### PR TITLE
Disable s390 builds for clang 12 and earlier on mainline

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Review by nickdesaulniers — APPROVED** [review]
😞 😿

**Comment by ojeda** [comment]
Sorry to hijack the PR -- so is s390 not working under LLVM 12 now? (again?)

I was planning to add this one as the next arch for Rust for Linux :-(

**Comment by sylvestre** [comment]
if it helps and not too complex, I could backport the fix into apt.llvm.org

**Comment by nathanchance** [comment]
> Sorry to hijack the PR -- so is s390 not working under LLVM 12 now? (again?)
> 
> I was planning to add this one as the next arch for Rust for Linux :-(

Yes, see https://git.kernel.org/linus/e2bc3e91d91ede6710801fa0737e4e4ed729b19e for the reasoning.

> if it helps and not too complex, I could backport the fix into apt.llvm.org

Unfortunately, due to the commit above, that will not do anything :(

**Comment by ojeda** [comment]
Thanks Nathan! Understood -- let's wait for LLVM 13 then :)

**Pull request merged**
