### PR TITLE
Enable more configurations for ARCH=arm

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Do these fail to boot?

**Comment by nathanchance** [comment]
I did not try. I figured `omap2plus_defconfig` and `imx_v4_v5_defconfig` probably wouldn't boot under the QEMU virt CPU and I forgot to test the LPAE config.

**Comment by nathanchance** [comment]
Okay, I have enabled the testing for the LPAE config but the other two configs will not work with `boot-qemu.sh` in its current form since we boot specific v5 and v6 machines.

**Comment by nathanchance** [comment]
I am going to merge this without explicit approval after our conversation offline. Please scream if you see anything wrong after the fact and I am more than happy to push subsequent fixups.

**Pull request merged**
