### PR TITLE
enable LLVM_IAS=1 android x86 builds

### PR DESCRIPTION
**Pull request by nickdesaulniers**
two commits, one enables x86 since https://gitlab.com/Linaro/tuxmake/-/issues/117 is marked fixed. The other re-enables LLVM_IAS=1.

### CODE REVIEW

**Comment by nathanchance** [comment]
I just tested with `tuxmake` locally and I am not sure that this will pass: https://gitlab.com/Linaro/tuxmake/-/issues/117#note_500946481

I think 4.19 is going to still be broken regardless of that though: https://github.com/ClangBuiltLinux/linux/issues/1269

I will try to tackle that tomorrow.

**Comment by nathanchance** [comment]
The `tuxmake` issue seems to be something on my end I guess. This needs to be rebased on latest main and have the workflow files regenerated. It is up to you if we disable x86_64 defconfig for 4.19, it will just be broken for the time being: https://builds.tuxbuild.com/1o1mS4y3G2efrRxXYaD48FVVPGP/

**Review by nathanchance — APPROVED** [review]
LGTM.

**Comment by nickdesaulniers** [comment]
I'll follow up with disabling the known broken branch if we don't resolve the KI soon.

**Pull request merged**
